config/routes.rb
Rails.application.routes.draw do

	# get '/listings' => 'listings#index'
	# get 'listings/new' => 'listings#new'

  
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  resources :listings do
  	resources :photos
  end

  resources :users 

  #root page
  root to: 'listings#index'

end

app/models/listing.rb
class Listing
  include Mongoid::Document
  field :type, type: String
  field :address, type: String
  field :city, type: String
  field :state, type: String
  field :zip, type: Integer
  field :num_bed, type: Integer
  field :num_bath, type: Integer
  field :price, type: Integer
  field :description, type: String
  field :latitude, type: Float
  field :longitude, type: Float
  mount_uploader :photo, ListingPhotoUploader
  embeds_many :photos
  belongs_to :user
  

 	validates :type, presence: true
  validates :city, presence: true
  validates :num_bed, presence: true
  validates :num_bath, presence: true
  validates :price, presence: true
  validates :description, presence: true

  def full_address
    return "#{address}, #{city}, #{state}, #{zip}"
  end
end

app/models/photo.rb
class Photo
  include Mongoid::Document
  field :url, type: String
  mount_uploader :photo, ListingPhotoUploader
  embedded_in :listing
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  field :username, type: String
  field :email, type: String
  field :password_digest, type: String
  has_many :listings

  has_secure_password

  validates :email, uniqueness: true
  validates :username, uniqueness: true
  validates :password, confirmation: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def current_user
  	@current_user ||= User.find(session[:user_id]['$oid']) if session[:user_id]
  end
	helper_method :current_user

  def authorize
  	unless current_user
  		redirect_to login_path
  	end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

		before_action :authorize, except: [:show, :index]

  def index
    # city search function for the listings 
    if params[:search]
      @listings = Listing.where(:city => params[:search].downcase)
    else
      @listings = Listing.all
    end
  end

  def show
      @listing = Listing.find(params[:id])
  end

  def new
      @listing = Listing.new
  end

  def create
      @listing = current_user.listings.new(listing_params)
      
      # getting the latitude & the longitude using geokit gem/Geocoder to request geocode of the address entered, used to display pin on map
      @listing.latitude = Geokit::Geocoders::GoogleGeocoder.geocode(@listing.full_address).latitude
      @listing.longitude = Geokit::Geocoders::GoogleGeocoder.geocode(@listing.full_address).longitude
      
      @listing[:city].downcase!

    if @listing.save
      flash[:success] = "Listing created!"
      redirect_to listings_path
    else
      flash[:danger] = "All Fields are Required"
      render :new
    end
  end

  def edit
      @listing = Listing.find(params[:id])
  end
  
  def update
      #saves update listing
      @listing = Listing.find(params[:id])
  
    if @listing.update(listing_params)
      redirect_to listing_path
    else
      render :edit
    end
  end
  
  def destroy
      @listing = Listing.find(params[:id])
     
      @listing.destroy
     
      redirect_to listings_path
  end

  private
  
  def listing_params
      params.require(:listing).permit(:type, :address, :city, :state, :zipcode, :num_bed, :num_bath, :price, :description, :photo, :latitude, :longitude)
  end
  
  end 

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def new
		@listing = Listing.find(params[:listing_id])
	  @photo = Photo.new
	end

	def create
		# adding new photo to the listing / pushing new photo to the photo array
		@listing = Listing.find(params[:listing_id])
	  @listing.photos.push( Photo.new(params.require(:photo).permit(:photo)) )
	  if @listing.save
	  	redirect_to listing_path(@listing)
	  end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		#user authentication required/added flash messages.
		user = User.find_by(username: params[:user][:username])
		if user && user.authenticate(params[:user][:password])

			flash[:success] = "Login Successful"
			session[:user_id] = user.id
			redirect_to user_path(user.id)
		else
			flash.now[:danger] = "Unable to Login, Please try again!"
			render :new
		end
	end

	def destroy
		#redirects to login page after user logs off
		session[:user_id]= nil
		redirect_to login_path
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# before_action :authorize
	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		#creates a user, after user signs up, redirects to login page.
		@user = User.new(params.require(:user).permit(:username, :email, :password, :password_confirmation))
		
		if @user.save
			redirect_to login_path
		else
			render :new
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doorknobapp</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyAtMTyEHjwug0bqEL-IEuEKgW3paGNZ0Jk" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!-- navigation bar -->

  <body>
    <header class="navbar navbar-inverse" role="navigation">
      <div class="navbar">
        <%= link_to "DoorKnob", '/listings', id: "logo" %>
      </div>
      <nav>
        <div class="links">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
            <li> Hello <%= current_user.username.upcase %>, You are logged in as <%= current_user.email %> </li>
            <li><%= link_to "Log Out", logout_path %></li>
            <% else %>
            <li><%= link_to "Sign Up", '/users/new' %></li>
            <li><%= link_to "Login",   login_path %></li>
            <li><%= link_to "Log Out", logout_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div> 
  </header>


  <!-- user sees add listing link if logged in -->

  <div class="container">
   <% if current_user %>
   <% flash.each do |key, value| %>
   <div class="alert alert-<%= key %>" role="alert">
    <% key %><%= value %>
  </div>
  <% end %>
  <div class ="pager"><%= link_to 'See All Listings', listings_path, :class => "btn btn-info" %>   <%= link_to 'Add A New Listing', new_listing_path, :class => "btn btn-info" %></div>
  <% else %>
  <%#= link_to 'login', login_path %>
  <% end %>

  <%= yield %>
  

</body>

</html>

app/views/listings/edit.html.erb
 <!-- form for editing a listing -->
 <form>
  <%= form_for @listing do |f| %>

  Type: <%= f.text_field :type %><br>
  City: <%= f.text_field :city %><br>
  Bedrooms: <%= f.number_field :num_bed %><br>
  Bathrooms: <%= f.number_field :num_bath %><br>
  Price: $ <%= f.number_field :price %><br>
  Description: <%= f.text_area :description %><br>
  Listing Thumbnail <%= f.file_field :photo, :multiple => true %></br><br>
  <br>
  <%= f.submit 'Update' %>
  
  <% end %>
</form>

app/views/listings/index.html.erb
<!-- index page view for when user is logged in -->
<% if current_user %>
<div id="map-container">
  <div id="map-canvas">
  </div>
</div>
<script type="text/javascript">
function initialize() {
  var myLatlng;
  // The current zoom and location of where the map is centerd on
  navigator.geolocation.getCurrentPosition(function(position) {
    myLatlng =(new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
    console.log(myLatlng);
  // var myLatlng = makeLatLng(34.05, -118.2);
      var mapOptions = {
        zoom: 11,
        center: myLatlng
      }

  // Create a map with a canvas
  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);


  // The function to create a longitude and latitude in Google Maps
  function makeLatLng(latitude, longitude) {
    return new google.maps.LatLng(latitude, longitude)
  }

  //The function to create a marker in Google Maps
  function makeMarker(latitude, longitude) {
    return new google.maps.Marker({
      position: makeLatLng(latitude, longitude),
      map: map,
    });
  }

  // Add saved longitudes and latitudes to save on the map
  <% @listings.each do |listing| %>

  var <%= "marker" + listing.id %> = makeMarker(<%= listing.latitude %>, <%= listing.longitude %>);
  console.log(listing)
  var <%= "infoWindow" + listing.id %> = new google.maps.InfoWindow({
    content: '<span><strong>Address:</strong> <%= listing.address %></span><br> <span><%= listing.city %>, <%= listing.state %> <%= listing.zip %></span><br> <span><strong>Description:</strong> <%= listing.description %></span>'
  });

  google.maps.event.addListener(<%= "marker" + listing.id %>, 'click', function() {
    <%= "infoWindow" + listing.id %>.open(map,<%= "marker" + listing.id %>);
    setTimeout(function(){ <%= "infoWindow" + listing.id %>.close(map,<%= "marker" + listing.id %>); }, 2000);
  });
  <% end %>

});

}

// Loads Google Map on window load
google.maps.event.addDomListener(window, 'load', initialize);
</script>

<table>

  <tbody>
    <table class="table table-hover">
    <% @listings.each do |f| %>
      <tr>
        <td><%= f.type %></td>
        <td><%= f.address %></td>
        <td><%= f.city.capitalize %> 
        <td><%= f.state %></td>
        <td><%= f.zip %></td>
        <td><%= f.num_bed %></td>
        <td><%= f.num_bath %></td>
        <td>$<%= f.price %></td>
        <td><%= f.description %></td>
        <td><%= image_tag f.photo.url(:small), height: '150', width: '130' %></td>
        <td><%= link_to 'See More', listing_path(f), :class => "btn btn-info" %></td>
      </tr>
    <% end %>
  </table>
  </tbody>

</table>
<%else%>
<!-- Landing Page with three slides-->
<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="4000" id="bs-carousel">
  <!-- Overlay -->
  <div class="overlay"></div>

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#bs-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#bs-carousel" data-slide-to="1"></li>
    <li data-target="#bs-carousel" data-slide-to="2"></li>
  </ol>
  
  <!-- Wrapper for slides -->
  <div class="carousel-inner">

    <div class="item slides active">
      <div class="slide-1">
        <div class="hero">
          <hgroup>
            <h1>Find your next home</h1>        
            <%= form_tag listings_path, :method => 'get' do %>
            <%= text_field_tag :search, params[:search], :placeholder => "ENTER CITY", :style =>"color: black;" %><br>
            <%= submit_tag "Take Me There", :class => "btn btn-hero btn-lg" %>
            <% end %>
          </hgroup>
        </div>
      </div>
    </div>

    <div class="item slides">
      <div class="slide-2"></div>
      <div class="hero">        
        <hgroup>
          <h1>Join the Community</h1>        
        </hgroup>  
        <%= button_to "Sign Up", new_user_path,
        :class => "btn btn-hero btn-lg", :method => :get %>
      </div>
    </div>

    <div class="item slides">
      <div class="slide-3"></div>
      <div class="hero">        
        <hgroup>
          <h1>Post your Space</h1>        
        </hgroup>
        <%= button_to "LOGIN", login_path,
        :class => "btn btn-hero btn-lg", :method => :get %>
      </div>
    </div>
  </div>
</div>

  <!-- listing info view for logged in users -->

  <table>
    <tbody>
      <table class="table table-hover">
        <% @listings.each do |f| %>
        <tr>
          <td><%= f.type %></td>
          <td><%= f.address %></td>
          <td><%= f.city.capitalize %> 
            <td><%= f.state %></td>
            <td><%= f.zip %></td>
            <td><%= f.num_bed %></td>
            <td><%= f.num_bath %></td>
            <td>$<%= f.price %></td>
            <td><%= f.description %></td>
            <td><%= image_tag f.photo.url(:small), height: '150', width: '130' %></td>
            <%if current_user %>
            <td><%= link_to 'See More', listing_path(f), :class => "btn btn-info" %></td>
            <% else %>
            <td><%= link_to "Login to see more", login_path, :class => "btn btn-info" %></td>
            <% end %>
          </tr>
          <% end %>
        </table>
      </tbody>

    </table>
    <%end%>

app/views/listings/new.html.erb
<!-- add listing page view -->

<div class="form-group">
<%= form_for @listing do |f| %>

	<%= f.select :type, options_for_select(["House", "Condo", "Townhouse", "Apartment", "Roomshare"])%><br>
	<br>
	<%= f.text_field :address, :placeholder=>"Address" %><br>
  <br>
  <%= f.text_field :city, :placeholder=>"City" %><br>
 	<br>
  <%= f.text_field :state, :placeholder=>"State" %><br>
  <br>
  <%= f.number_field :zip, :placeholder=>"Zipcode" %><br>
  Bedrooms <br>
 	<%= f.select :num_bed, options_for_select([0, 1, 2, 3, 4, 5, 6, 7])%><br>
  Bathrooms <br>
  <%= f.select :num_bath, options_for_select([0, 1, 2, 3, 4, 5, 6, 7])%><br>
  <%= f.number_field :price, :placeholder=>"How Much is Rent?" %><br>
  Description: <br>
  <%= f.text_area :description, :placeholder=>"Tell us a bit about the place." %><br>
  6 Photos Minimum 
  <br><%= f.file_field :photo %><br>
  
  <%= f.submit 'Create Listing', :class => "btn btn-info" %>
  
<% end %>
</form>

app/views/listings/show.html.erb
<!-- view page for individual listings -->

<div class="form-group">
	Type: <%= @listing.type %> <br>
	Address: <%= @listing.address %><br>
	City: <%= @listing.city %><br>
	State: <%= @listing.state %><br>
	Zipcode : <%= @listing.zip %><br>
	Bedrooms: <%= @listing.num_bed %><br>
	Bathrooms: <%= @listing.num_bath %><br>
	Price: $ <%= @listing.price %><br>
	Description: <%= @listing.description %><br>
	Photos: <%= image_tag @listing.photo.url, height: '150', width: '130' %><br>
</div>

<% @listing.photos.each do |p| %>
<%= image_tag p.photo.url, height: '250', width: '230' %>
<%#= link_to "Delete this photo", :class => "btn btn-default" %>
<% end %>

<!-- editing options for logged in user -->

<div class="form-group">
	<% if current_user %>
	<%= link_to "Add Photos", new_listing_photo_path(@listing), :class => "btn btn-info" %>
	<%= link_to "Edit Listing", edit_listing_path, :class => "btn btn-warning" %>
	<%= link_to "Remove listing", :listing, method: :delete, data: { confirm: "Are you sure you want to delete this listing?"},  :class => "btn btn-danger" %>
	<% else %>
	<%= link_to "Back to the list", listings_path, :class => "btn btn-info" %>
	<% end %>
</div>

</div>

app/views/photos/new.html.erb
<!-- photo upload page view -->
<%= form_for [@listing, @photo] do |f| %>
	<%= f.file_field :photo %>
	<%= f.submit 'Add Photo', :class => "btn btn-info" %>
<% end %>

app/views/users/new.html.erb
<!-- sign up page view -->
<div class="form-group">
	<h1>Create New User</h1> 
	<%= form_for @user do |f| %>
	USERNAME<br> <%= f.text_field :username %><br>
	EMAIL <br><%= f.text_field :email %><br>
	PASSWORD <br> <%= f.password_field :password %><br>
	CONFIRM YOUR PASSWORD <br><%= f.password_field :password_confirmation %><br><br>
	<%= f.submit "Join", :class => "btn btn-info" %>
	<% end %>
</div>